### ISSUE TITLE
Support PHP Baselines

### ISSUE THREAD

**Issue by dpi** [shipmonk-rnd/phpstan-baseline-per-identifier#11]
Is it possible for this project to support PHP baselines instead of NEON?

https://phpstan.org/user-guide/baseline#php-baseline-format-instead-of-neon

**Comment by janedbal** [comment]
I'm about to change the approach of this extension (to be released as 2.0 along with PHPStan 2.0 support) to utilize native baseline generation as much as possible in https://github.com/shipmonk-rnd/phpstan-baseline-per-identifier/pull/10. With that, PHP baseline can be supported.

**Comment by janedbal** [comment]
Released in [2.0.0](https://github.com/shipmonk-rnd/phpstan-baseline-per-identifier/releases/tag/2.0.0)
