### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by simbig** [shipmonk-rnd/phpstan-baseline-per-identifier#19]
## Problem 
The `phpstan-baseline-per-identifier library` currently only supports PHP 8.0. Unfortunately, one of my current projects is limited to using PHP 7.4. This prevents me from utilizing the valuable features of this library.

## Suggestion
To enable the use of PHP ^8 features while maintaining backward compatibility with PHP 7.4, I'd propose implementing a strategy similar to the one outlined in this blog post: https://tomasvotruba.com/blog/how-to-release-php-81-and-72-package-in-the-same-repository/ and done in this repo: https://github.com/TomasVotruba/cognitive-complexity/blob/main/.github/workflows/downgraded_release.yaml

This approach involves:

- Maintaining a Single Codebase: Continue developing in a single repository.
- Downgrading for PHP 7.4 Releases: Implement a build process to downgrade the codebase and dependencies to PHP 7.4 for specific releases.

 If the project maintainers are interested in exploring this option, I would be happy to contribute a pull request to implement it.

**Comment by janedbal** [comment]
Released as [2.1.0](https://github.com/shipmonk-rnd/phpstan-baseline-per-identifier/releases/tag/2.1.0), thank you!
