### ISSUE TITLE
Generate smarter loader

### ISSUE THREAD

**Issue by ruudk** [shipmonk-rnd/phpstan-baseline-per-identifier#25]
I think _one_ of the use cases for this package is to be able to work on a single problem (error identifier) at a time. 

My ideal workflow would be to be able to delete a specific error identifier baseline and then run PHPStan.

Then see the errors, click the line where the error is happening, and fix it one by one.

But there is one problem with this: you also have to edit the loader.php file.

It would be great if the loader.php would read all the files in the directory automatically, and load them. 

Something like this:
```php
$files = Finder::create()->files()->name('*.php')->sortByName()->in(__DIR__ . '/src-dev/PHPStan/baselines');

return [
    'includes' => [
        ...array_values(array_map(fn ($file) => $file->getRealPath(), iterator_to_array($files))),
    ],
```

For now, I can solve this by not using the generated loader.php file, and manually include the baselines. 

But it might be good to support this here too.

**Comment by janedbal** [comment]
> But there is one problem with this: you also have to edit the loader.php file.

I'm not sure I fully understand. What is the issue with adjusting loader file? 

Also, just to see the errors, I think you can delete just contents of the single baseline (to maintain result cache usage).

**Comment by ruudk** [comment]
Sure, that also works, but it's more work. 

With the finder method, it automatically works when you remove the file. Just an idea.

**Comment by janedbal** [comment]
I dont feel implementing that directly, sorry. 

The only support for this I can imagine is to add some support for custom [BaselineHandler](https://github.com/shipmonk-rnd/phpstan-baseline-per-identifier/blob/master/src/Handler/BaselineHandler.php), possibly via some `--handler=My\Custom\BaselineHandler`. Then, you could do whatever you like.

**Comment by ruudk** [comment]
Ok, thanks.

For now, I can do it easily like this:
```
 "generate:baseline:phpstan": [
            "vendor/bin/phpstan analyse --memory-limit=-1 --configuration=phpstan.php --generate-baseline src-dev/PHPStan/config/baseline/loader.php",
            "split-phpstan-baseline src-dev/PHPStan/config/baseline/loader.php",
            "rm -f src-dev/PHPStan/config/baseline/loader.php"
        ]
```

```php
$files = Finder::create()
    ->files()
    ->name('*.php')
    ->sortByName()
    ->in(__DIR__ . '/src-dev/PHPStan/config')
    ->notName('baseline-loader.php');

return [
    'includes' => [
        ...array_values(array_map(fn ($file) => $file->getRealPath(), iterator_to_array($files))),
    ],
```
