### ISSUE TITLE
PHP baselines - missing slash in path 

### ISSUE THREAD

**Issue by jmdelehaye** [shipmonk-rnd/phpstan-baseline-per-identifier#30]
Thanks for this great project!

I'm trying to use the PHP baselines implemented in #11, and it doesn't work for me.

It seems that there is a missing slash in the path:
* actual: `'path' => __DIR__ . '../myFile `
* expected: `'path' => __DIR__ . '/../myFile`

**Comment by janedbal** [comment]
Fixed in https://github.com/shipmonk-rnd/phpstan-baseline-per-identifier/pull/32, thank you!
