### ISSUE TITLE
New major version of PHPStan

### ISSUE THREAD

**Issue by deadbublik** [shipmonk-rnd/phpstan-baseline-per-identifier#7]
Hello!
Thanks for your work and for this package!

PHPStan has released a new major version - https://github.com/phpstan/phpstan/releases/tag/2.0.0
Could you update your package to support this version?

**Comment by janedbal** [comment]
Released in [2.0.0](https://github.com/shipmonk-rnd/phpstan-baseline-per-identifier/releases/tag/2.0.0)
